name: Bug Report
description: Create a bug report to help improving our addons.
title: 'Bug: <title>'
labels: ['bug']
assignees: 'BlenderDefender'

body:
  - type: markdown
    attributes:
      value: "## Bug Description"
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## System Information"
  - type: dropdown
    id: operating_system
    attributes:
      label: "Operating System"
      description: What operating system are you using? (You may select more than one)
      multiple: true
      options:
        - Windows 10
        - Windows 11
        - Linux
        - MacOS
      default: 0
    validations:
      required: true
  - type: dropdown
    id: blender_version
    attributes:
      label: "Blender Version"
      description: Which Blender version are you using? (You may select more than one)
      multiple: true
      options:
        - Blender 4.0 (latest)
        - Blender 3.6 LTS
        - Blender 3.5
        - Blender 3.4
        - Blender 3.3 LTS
        - Blender 3.2 or lower (please specify under "Additional Information")
      default: 0
    validations:
      required: true
  - type: input
    id: addon_version
    attributes:
      label: "Addon Version"
      description: Which version of this addon are you experiencing issues with?
      placeholder: "Example: Version 1.2.1"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Additional Information"
  - type: textarea
    id: additional_context
    attributes:
      label: Screenshots and additional context
      description: If applicable, add screenshots, log files, error messages, ... to help explain your problem.
