name: Bug Report
description: "Report an issue"
body:
  - type: checkboxes
    id: os
    attributes:
      label: Test
      description: You may select more than one
      options:
        - label: MacOS
        - label: Windows
        - label: Linux
  - type: dropdown
    id: t
    attributes:
      label: What version of Blender are you using?
      options:
        - 2.83
        - 2.90
        - 2.91
        - 2.92
        - 2.93
        - 3.0
        - 3.1
        - 3.1
      validations:
        required: true
